version: "3.9"

services:
  web:
    build: .
    container_name: proyecto_asoftware_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
