# Generated by Django 5.1.1 on 2025-09-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_itemcarrito_unique_together'),
        ('catalog', '0004_remove_producto_id_categoria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together={('carrito', 'producto')},
        ),
    ]
