# Generated by Django 5.1.6 on 2025-08-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], default='hombre', max_length=10, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('camiseta', 'Camiseta'), ('buzo', 'Buzo'), ('pantalon', 'Pantalón')], default='camiseta', max_length=30, verbose_name='Tipo de prenda'),
        ),
    ]
