# Generated by Django 5.1.1 on 2025-11-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_producto_id_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion_en',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_es',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_es',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
