# Generated by Django 5.0.6 on 2025-11-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_producto_descripcion_en_producto_descripcion_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion_en',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion_es',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre_en',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre_es',
        ),
    ]
