# Generated by Django 5.1.6 on 2025-08-30 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_producto_imagen_historialbusqueda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_categoria',
        ),
    ]
