# Generated by Django 5.1.1 on 2025-09-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0004_remove_producto_id_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carritocompra',
            options={'ordering': ['-id'], 'verbose_name': 'Carrito de compra', 'verbose_name_plural': 'Carritos de compra'},
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together={('carrito', 'producto')},
        ),
    ]
