# Generated by Django 5.1.1 on 2025-09-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_carritocompra_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together=set(),
        ),
    ]
